server:
  port: ${PORT:8085}
  servlet:
    context-path: /hk

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
  session:
    timeout: 3600

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hkapp
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: WARN
    com.hkapp: DEBUG
    org.springframework.web: DEBUG
