server:
  port: 8085
  servlet:
    context-path: /hk

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  session:
    timeout: 3600

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: WARN
    com.example: INFO
